version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "frontendContainerDev"
          ContainerPort: 80
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
